server:
  port: 8081
eureka:
  client:
    service-url:
#     defaultZone: http://localhost:1111/eureka,http://localhost:1112/eureka
     defaultZone: http://localhost:1111/eureka
spring:
  application:
    name: sun-client-first